/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.WatchIS.view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Santoshi Paudel
 * LMU ID: 23048656
 */
public class Watch extends javax.swing.JFrame {
    private java.awt.CardLayout cardLayout;
    
    public Watch() {
        initComponents();
        initializeLayout(); // Set up CardLayout and add screens
        Progress(); // Show loading screen and initiate progress
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLoginScreen = new javax.swing.JPanel();
        pnlLoginImage = new javax.swing.JPanel();
        lblLoginImage = new javax.swing.JLabel();
        lblLoginTitle = new javax.swing.JLabel();
        lblLoginDesc = new javax.swing.JLabel();
        txtFldPassword = new javax.swing.JTextField();
        txtFldUserName = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        ckBoxRemember = new javax.swing.JCheckBox();
        lblForgotPassword = new javax.swing.JLabel();
        pnlLoginLogo = new javax.swing.JPanel();
        lblLoginLogoImage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlWatchInfoScreen = new javax.swing.JPanel();
        pnlMainBar = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblInfoscreenLogo = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        tabPaneWatchInfo = new javax.swing.JTabbedPane();
        pnlHome = new javax.swing.JPanel();
        pnlHomeDetails = new javax.swing.JPanel();
        lblHomeWording = new javax.swing.JLabel();
        lblHomeWording1 = new javax.swing.JLabel();
        lblHomeWording2 = new javax.swing.JLabel();
        lblHomeWording4 = new javax.swing.JLabel();
        lblhomeWording5 = new javax.swing.JLabel();
        lblHomeImage = new javax.swing.JLabel();
        lblWatchImage = new javax.swing.JLabel();
        lblHomeWatchImage = new javax.swing.JLabel();
        lblWatchImageHome = new javax.swing.JLabel();
        lblTimex = new javax.swing.JLabel();
        lblMatteWork = new javax.swing.JLabel();
        lbl5k = new javax.swing.JLabel();
        lblWarranty = new javax.swing.JLabel();
        lblYears = new javax.swing.JLabel();
        lblSale = new javax.swing.JLabel();
        pnlAboutUs = new javax.swing.JPanel();
        lblAboutUsWording = new javax.swing.JLabel();
        lblAboutUsHeading = new javax.swing.JLabel();
        lblAboutUsWording1 = new javax.swing.JLabel();
        lblAboutUsWording2 = new javax.swing.JLabel();
        lblAboutUsWording3 = new javax.swing.JLabel();
        lblAboutUsWording4 = new javax.swing.JLabel();
        lblAboutUsWording5 = new javax.swing.JLabel();
        lblAboutUsWording6 = new javax.swing.JLabel();
        lblAboutUsImage = new javax.swing.JLabel();
        lblExperiences = new javax.swing.JLabel();
        lblExperiences1 = new javax.swing.JLabel();
        pnlWatchCollections = new javax.swing.JPanel();
        lblWatchdetails = new javax.swing.JLabel();
        scrlPaneWatchInfo = new javax.swing.JScrollPane();
        scrlPaneWatchDetails = new javax.swing.JScrollPane();
        tblWatchInfo = new javax.swing.JTable();
        lblForm = new javax.swing.JLabel();
        tfSerialNumber = new javax.swing.JTextField();
        tfModelNumber = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfBrand = new javax.swing.JTextField();
        tfPrice = new javax.swing.JTextField();
        tfWarranty = new javax.swing.JTextField();
        btnAddWatch = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        pnlContactUs = new javax.swing.JPanel();
        lblContactImage = new javax.swing.JLabel();
        lblContactHeading = new javax.swing.JLabel();
        pnlContact = new javax.swing.JPanel();
        txtFldName = new javax.swing.JTextField();
        txtFldEmail = new javax.swing.JTextField();
        lblContactFill = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaMessage = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        pnlMainScreen = new javax.swing.JPanel();
        lblLogoImage = new javax.swing.JLabel();
        pgBarSplashScreen = new javax.swing.JProgressBar();
        lblWelcomePage = new javax.swing.JLabel();
        lblWait = new javax.swing.JLabel();
        lblWelcomeDescription = new javax.swing.JLabel();
        lblMotto = new javax.swing.JLabel();

        pnlLoginScreen.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoginScreen.setMaximumSize(new java.awt.Dimension(1000, 1000));
        pnlLoginScreen.setPreferredSize(new java.awt.Dimension(1000, 1000));
        pnlLoginScreen.setSize(new java.awt.Dimension(1000, 1000));

        pnlLoginImage.setBackground(new java.awt.Color(255, 255, 255));

        lblLoginImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/WatchIS/resources/homeWatch.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlLoginImageLayout = new javax.swing.GroupLayout(pnlLoginImage);
        pnlLoginImage.setLayout(pnlLoginImageLayout);
        pnlLoginImageLayout.setHorizontalGroup(
            pnlLoginImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLoginImage, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlLoginImageLayout.setVerticalGroup(
            pnlLoginImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginImageLayout.createSequentialGroup()
                .addComponent(lblLoginImage)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblLoginTitle.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lblLoginTitle.setForeground(new java.awt.Color(3, 37, 76));
        lblLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginTitle.setText("SIGN IN");

        lblLoginDesc.setBackground(new java.awt.Color(0, 0, 0));
        lblLoginDesc.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblLoginDesc.setForeground(new java.awt.Color(0, 102, 204));
        lblLoginDesc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLoginDesc.setText("Please Fill Your Details Below To Login To Our Page ");

        txtFldPassword.setBackground(new java.awt.Color(3, 37, 76));
        txtFldPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtFldPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFldPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("ITF Devanagari", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldPasswordActionPerformed(evt);
            }
        });

        txtFldUserName.setBackground(new java.awt.Color(3, 37, 76));
        txtFldUserName.setForeground(new java.awt.Color(255, 255, 255));
        txtFldUserName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFldUserName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("ITF Devanagari", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldUserNameActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(233, 177, 8));
        btnLogin.setFont(new java.awt.Font("Devanagari MT", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 51, 153));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        ckBoxRemember.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ckBoxRemember.setForeground(new java.awt.Color(3, 37, 76));
        ckBoxRemember.setText("Remember Me");
        ckBoxRemember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckBoxRememberActionPerformed(evt);
            }
        });

        lblForgotPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblForgotPassword.setForeground(new java.awt.Color(0, 51, 102));
        lblForgotPassword.setText("Forgot Password?");

        pnlLoginLogo.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoginLogo.setForeground(new java.awt.Color(255, 153, 0));

        lblLoginLogoImage.setFont(new java.awt.Font("Herculanum", 1, 24)); // NOI18N
        lblLoginLogoImage.setForeground(new java.awt.Color(3, 37, 76));
        lblLoginLogoImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginLogoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/WatchIS/resources/Watch copy 2.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Herculanum", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("\"Your Wrist Deserves the Best\"");

        javax.swing.GroupLayout pnlLoginLogoLayout = new javax.swing.GroupLayout(pnlLoginLogo);
        pnlLoginLogo.setLayout(pnlLoginLogoLayout);
        pnlLoginLogoLayout.setHorizontalGroup(
            pnlLoginLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLogoLayout.createSequentialGroup()
                .addComponent(lblLoginLogoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLoginLogoLayout.setVerticalGroup(
            pnlLoginLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLogoLayout.createSequentialGroup()
                .addComponent(lblLoginLogoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlLoginLogoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlLoginScreenLayout = new javax.swing.GroupLayout(pnlLoginScreen);
        pnlLoginScreen.setLayout(pnlLoginScreenLayout);
        pnlLoginScreenLayout.setHorizontalGroup(
            pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                .addComponent(pnlLoginImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                            .addGap(159, 159, 159)
                            .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                                        .addComponent(ckBoxRemember, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblForgotPassword))
                                    .addComponent(txtFldPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(lblLoginDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pnlLoginLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginScreenLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(216, 216, 216)))
                    .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLoginScreenLayout.setVerticalGroup(
            pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLoginImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlLoginScreenLayout.createSequentialGroup()
                .addComponent(pnlLoginLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(lblLoginTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLoginDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(txtFldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblForgotPassword)
                    .addComponent(ckBoxRemember))
                .addGap(45, 45, 45)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlWatchInfoScreen.setBackground(new java.awt.Color(3, 37, 76));
        pnlWatchInfoScreen.setBounds(new java.awt.Rectangle(0, 0, 1000, 1500));
        pnlWatchInfoScreen.setMaximumSize(new java.awt.Dimension(1000, 1500));
        pnlWatchInfoScreen.setPreferredSize(new java.awt.Dimension(1000, 1500));

        pnlMainBar.setBackground(new java.awt.Color(255, 255, 255));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/WatchIS/resources/Watch copy 2.png"))); // NOI18N

        lblInfoscreenLogo.setFont(new java.awt.Font("Sukhumvit Set", 1, 36)); // NOI18N
        lblInfoscreenLogo.setForeground(new java.awt.Color(255, 153, 51));
        lblInfoscreenLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoscreenLogo.setText("\"Your Wrist Deserves The Best\"");

        btnLogOut.setBackground(new java.awt.Color(0, 102, 153));
        btnLogOut.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainBarLayout = new javax.swing.GroupLayout(pnlMainBar);
        pnlMainBar.setLayout(pnlMainBarLayout);
        pnlMainBarLayout.setHorizontalGroup(
            pnlMainBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoscreenLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogOut)
                .addContainerGap(1499, Short.MAX_VALUE))
        );
        pnlMainBarLayout.setVerticalGroup(
            pnlMainBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainBarLayout.createSequentialGroup()
                .addGroup(pnlMainBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMainBarLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pnlMainBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInfoscreenLogo)
                            .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabPaneWatchInfo.setBackground(new java.awt.Color(3, 37, 76));
        tabPaneWatchInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabPaneWatchInfo.setForeground(new java.awt.Color(255, 255, 255));
        tabPaneWatchInfo.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabPaneWatchInfo.setAlignmentX(2.0F);
        tabPaneWatchInfo.setAlignmentY(2.0F);
        tabPaneWatchInfo.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N

        pnlHome.setBackground(new java.awt.Color(3, 37, 76));

        pnlHomeDetails.setBackground(new java.awt.Color(3, 37, 76));

        lblHomeWording.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblHomeWording.setForeground(new java.awt.Color(255, 153, 0));
        lblHomeWording.setText("Explore");

        lblHomeWording1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblHomeWording1.setForeground(new java.awt.Color(255, 255, 255));
        lblHomeWording1.setText("The");

        lblHomeWording2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblHomeWording2.setForeground(new java.awt.Color(255, 255, 255));
        lblHomeWording2.setText("with Exceptional Accuracy.");

        lblHomeWording4.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblHomeWording4.setForeground(new java.awt.Color(255, 255, 255));
        lblHomeWording4.setText("High-Precision Timepieces that Blend elegence");

        lblhomeWording5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblhomeWording5.setForeground(new java.awt.Color(255, 255, 255));
        lblhomeWording5.setText("High range of designer watches for both men and women.");

        lblHomeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/WatchIS/resources/canva-MAEnaWCLE-0.png"))); // NOI18N

        lblWatchImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/WatchIS/resources/Untitled design.jpg"))); // NOI18N
        lblWatchImage.setText("Timex");
        lblWatchImage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblHomeWatchImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/WatchIS/resources/Untitled design copy 2.jpg"))); // NOI18N

        lblWatchImageHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/WatchIS/resources/Untitled design copy 3.jpg"))); // NOI18N

        lblTimex.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblTimex.setForeground(new java.awt.Color(255, 255, 255));
        lblTimex.setText("Timex");

        lblMatteWork.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblMatteWork.setForeground(new java.awt.Color(255, 255, 255));
        lblMatteWork.setText("Matte Work");

        lbl5k.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbl5k.setForeground(new java.awt.Color(255, 255, 255));
        lbl5k.setText("Breitling");

        lblWarranty.setFont(new java.awt.Font("Herculanum", 1, 18)); // NOI18N
        lblWarranty.setForeground(new java.awt.Color(255, 255, 255));
        lblWarranty.setText("satisfiedcustomers         Warranty");

        lblYears.setFont(new java.awt.Font("Herculanum", 1, 24)); // NOI18N
        lblYears.setForeground(new java.awt.Color(255, 255, 255));
        lblYears.setText("5K+           |    3 Years");

        lblSale.setFont(new java.awt.Font("Luminari", 1, 18)); // NOI18N
        lblSale.setForeground(new java.awt.Color(255, 153, 0));
        lblSale.setText("Sale+     Luxury Watches+       Accessories+");

        javax.swing.GroupLayout pnlHomeDetailsLayout = new javax.swing.GroupLayout(pnlHomeDetails);
        pnlHomeDetails.setLayout(pnlHomeDetailsLayout);
        pnlHomeDetailsLayout.setHorizontalGroup(
            pnlHomeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeDetailsLayout.createSequentialGroup()
                .addGroup(pnlHomeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeDetailsLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(pnlHomeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHomeDetailsLayout.createSequentialGroup()
                                .addComponent(lblHomeWording)
                                .addGap(18, 18, 18)
                                .addComponent(lblHomeWording1))
                            .addComponent(lblHomeWording2)
                            .addComponent(lblhomeWording5)
                            .addComponent(lblHomeWording4)
                            .addComponent(lblSale, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlHomeDetailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblWatchImage, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lblHomeWatchImage)
                        .addGap(30, 30, 30)
                        .addComponent(lblWatchImageHome)))
                .addGap(0, 44, Short.MAX_VALUE)
                .addGroup(pnlHomeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeDetailsLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lblYears, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHomeDetailsLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(pnlHomeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWarranty, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHomeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(970, Short.MAX_VALUE))
            .addGroup(pnlHomeDetailsLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lblTimex, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275)
                .addComponent(lbl5k, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145)
                .addComponent(lblMatteWork, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHomeDetailsLayout.setVerticalGroup(
            pnlHomeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeDetailsLayout.createSequentialGroup()
                .addGroup(pnlHomeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeDetailsLayout.createSequentialGroup()
                        .addComponent(lblHomeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lblYears)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWarranty)
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addGroup(pnlHomeDetailsLayout.createSequentialGroup()
                        .addGroup(pnlHomeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHomeDetailsLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lblHomeWording1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeDetailsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblHomeWording)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHomeWording4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHomeWording2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblhomeWording5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSale)
                        .addGap(57, 57, 57)
                        .addGroup(pnlHomeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWatchImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHomeWatchImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlHomeDetailsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblWatchImageHome, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(pnlHomeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimex)
                    .addComponent(lbl5k)
                    .addComponent(lblMatteWork))
                .addGap(1796, 1796, 1796))
        );

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHomeDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(66, 66, 66))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlHomeDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabPaneWatchInfo.addTab("Home", pnlHome);

        pnlAboutUs.setBackground(new java.awt.Color(3, 37, 76));

        lblAboutUsWording.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 18)); // NOI18N
        lblAboutUsWording.setForeground(new java.awt.Color(255, 153, 0));
        lblAboutUsWording.setText("Safe, Versatile and Effecient Platform.");

        lblAboutUsHeading.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 36)); // NOI18N
        lblAboutUsHeading.setForeground(new java.awt.Color(255, 255, 255));
        lblAboutUsHeading.setText("About Us");

        lblAboutUsWording1.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 18)); // NOI18N
        lblAboutUsWording1.setForeground(new java.awt.Color(255, 255, 255));
        lblAboutUsWording1.setText("The watches provides full satisfaction to our customer with quality assurance. From our carefully selected materials   ");

        lblAboutUsWording2.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 18)); // NOI18N
        lblAboutUsWording2.setForeground(new java.awt.Color(255, 255, 255));
        lblAboutUsWording2.setText("At WatchX, You will find watches crafted to unites Classic elegence with precision and excellence.");

        lblAboutUsWording3.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 18)); // NOI18N
        lblAboutUsWording3.setForeground(new java.awt.Color(255, 255, 255));
        lblAboutUsWording3.setText("Every piece of creation tells a unique story blending innovation and tradition to offer more than just a watch. ");

        lblAboutUsWording4.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 18)); // NOI18N
        lblAboutUsWording4.setForeground(new java.awt.Color(255, 153, 0));
        lblAboutUsWording4.setText("Welcome to world of WatchX,where tradition meets innovations.");

        lblAboutUsWording5.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 18)); // NOI18N
        lblAboutUsWording5.setForeground(new java.awt.Color(255, 255, 255));
        lblAboutUsWording5.setText("to the fine details in every movement, we are committed to quality and excellence. ");

        lblAboutUsWording6.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 18)); // NOI18N
        lblAboutUsWording6.setForeground(new java.awt.Color(255, 255, 255));
        lblAboutUsWording6.setText("It is a Lifelong Companion.");

        lblAboutUsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/WatchIS/resources/canva-MAB-3k8i4eo.png"))); // NOI18N

        lblExperiences.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 18)); // NOI18N
        lblExperiences.setForeground(new java.awt.Color(210, 180, 140));
        lblExperiences.setText("Established Year       |        Number Of Users       |      Years Of Experience ");

        lblExperiences1.setFont(new java.awt.Font("Hiragino Mincho ProN", 0, 18)); // NOI18N
        lblExperiences1.setForeground(new java.awt.Color(210, 180, 140));
        lblExperiences1.setText("      2018                                   50K                                7+ years ");

        javax.swing.GroupLayout pnlAboutUsLayout = new javax.swing.GroupLayout(pnlAboutUs);
        pnlAboutUs.setLayout(pnlAboutUsLayout);
        pnlAboutUsLayout.setHorizontalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutUsLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAboutUsHeading)
                    .addComponent(lblAboutUsWording, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExperiences1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExperiences, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAboutUsWording4, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAboutUsWording1, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAboutUsWording2)
                    .addComponent(lblAboutUsWording3)
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addComponent(lblAboutUsWording5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAboutUsWording6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAboutUsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1387, Short.MAX_VALUE))
        );
        pnlAboutUsLayout.setVerticalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutUsLayout.createSequentialGroup()
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblAboutUsHeading)
                        .addGap(18, 18, 18)
                        .addComponent(lblAboutUsWording)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAboutUsWording2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAboutUsWording3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAboutUsWording1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAboutUsWording5)
                            .addComponent(lblAboutUsWording6))
                        .addGap(18, 18, 18)
                        .addComponent(lblAboutUsWording4)
                        .addGap(39, 39, 39)
                        .addComponent(lblExperiences, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblExperiences1))
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lblAboutUsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(491, Short.MAX_VALUE))
        );

        tabPaneWatchInfo.addTab("About Us", pnlAboutUs);

        pnlWatchCollections.setBackground(new java.awt.Color(3, 37, 76));

        lblWatchdetails.setFont(new java.awt.Font("STIX Two Text", 1, 36)); // NOI18N
        lblWatchdetails.setForeground(new java.awt.Color(255, 153, 0));
        lblWatchdetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWatchdetails.setText("Watch Details");

        scrlPaneWatchInfo.setBackground(new java.awt.Color(255, 255, 255));

        tblWatchInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblWatchInfo.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 18)); // NOI18N
        tblWatchInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial No", "Model No", "Name", "Brand", "Price", "Warranty"
            }
        ));
        tblWatchInfo.setSelectionBackground(new java.awt.Color(255, 255, 255));
        scrlPaneWatchDetails.setViewportView(tblWatchInfo);

        scrlPaneWatchInfo.setViewportView(scrlPaneWatchDetails);

        lblForm.setFont(new java.awt.Font("STIX Two Text", 1, 24)); // NOI18N
        lblForm.setForeground(new java.awt.Color(255, 153, 0));
        lblForm.setText("Watch Details Form");

        tfSerialNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Serial Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("STIX Two Text", 0, 18))); // NOI18N
        tfSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSerialNumberActionPerformed(evt);
            }
        });

        tfModelNumber.setForeground(new java.awt.Color(255, 255, 255));
        tfModelNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Model Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("STIX Two Text", 0, 18))); // NOI18N

        tfName.setForeground(new java.awt.Color(255, 255, 255));
        tfName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("STIX Two Text", 0, 18))); // NOI18N

        tfBrand.setForeground(new java.awt.Color(255, 255, 255));
        tfBrand.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Brand", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("STIX Two Text", 0, 18))); // NOI18N
        tfBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBrandActionPerformed(evt);
            }
        });

        tfPrice.setForeground(new java.awt.Color(255, 255, 255));
        tfPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("STIX Two Text", 0, 18))); // NOI18N
        tfPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPriceActionPerformed(evt);
            }
        });

        tfWarranty.setForeground(new java.awt.Color(255, 255, 255));
        tfWarranty.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Warranty", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("STIX Two Text", 0, 18))); // NOI18N
        tfWarranty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfWarrantyActionPerformed(evt);
            }
        });

        btnAddWatch.setBackground(new java.awt.Color(144, 127, 97));
        btnAddWatch.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnAddWatch.setForeground(new java.awt.Color(255, 255, 255));
        btnAddWatch.setText("ADD");
        btnAddWatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWatchActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(144, 127, 97));
        btnUpdate.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(144, 127, 97));
        btnDelete.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlWatchCollectionsLayout = new javax.swing.GroupLayout(pnlWatchCollections);
        pnlWatchCollections.setLayout(pnlWatchCollectionsLayout);
        pnlWatchCollectionsLayout.setHorizontalGroup(
            pnlWatchCollectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWatchCollectionsLayout.createSequentialGroup()
                .addComponent(lblWatchdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 1429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1455, Short.MAX_VALUE))
            .addGroup(pnlWatchCollectionsLayout.createSequentialGroup()
                .addGroup(pnlWatchCollectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlWatchCollectionsLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(pnlWatchCollectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrlPaneWatchInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 1122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlWatchCollectionsLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(pnlWatchCollectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlWatchCollectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlWatchCollectionsLayout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(lblForm))
                                    .addGroup(pnlWatchCollectionsLayout.createSequentialGroup()
                                        .addGap(119, 119, 119)
                                        .addGroup(pnlWatchCollectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(123, 123, 123)
                                        .addGroup(pnlWatchCollectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfWarranty, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(pnlWatchCollectionsLayout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(btnAddWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlWatchCollectionsLayout.setVerticalGroup(
            pnlWatchCollectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWatchCollectionsLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblWatchdetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrlPaneWatchInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblForm)
                .addGap(10, 10, 10)
                .addGroup(pnlWatchCollectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlWatchCollectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfWarranty, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlWatchCollectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(449, Short.MAX_VALUE))
        );

        tabPaneWatchInfo.addTab("Collections", pnlWatchCollections);

        pnlContactUs.setBackground(new java.awt.Color(3, 37, 76));

        lblContactImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/WatchIS/resources/contact.jpg"))); // NOI18N
        lblContactImage.setText("jLabel3");

        lblContactHeading.setFont(new java.awt.Font("Kannada MN", 1, 36)); // NOI18N
        lblContactHeading.setForeground(new java.awt.Color(255, 255, 255));
        lblContactHeading.setText("Contact Us");

        pnlContact.setBackground(new java.awt.Color(255, 255, 255));

        txtFldName.setBackground(new java.awt.Color(3, 37, 76));
        txtFldName.setForeground(new java.awt.Color(255, 255, 255));
        txtFldName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFldName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("ITF Devanagari", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldNameActionPerformed(evt);
            }
        });

        txtFldEmail.setBackground(new java.awt.Color(3, 37, 76));
        txtFldEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtFldEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFldEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-mail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("ITF Devanagari", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldEmailActionPerformed(evt);
            }
        });

        lblContactFill.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 24)); // NOI18N
        lblContactFill.setForeground(new java.awt.Color(255, 153, 0));
        lblContactFill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContactFill.setText("Leave Us Message");

        TxtAreaMessage.setBackground(new java.awt.Color(3, 37, 76));
        TxtAreaMessage.setColumns(20);
        TxtAreaMessage.setRows(5);
        TxtAreaMessage.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Message", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("ITF Devanagari Marathi", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jScrollPane1.setViewportView(TxtAreaMessage);

        btnSend.setBackground(new java.awt.Color(233, 177, 8));
        btnSend.setFont(new java.awt.Font("Devanagari MT", 1, 24)); // NOI18N
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContactLayout = new javax.swing.GroupLayout(pnlContact);
        pnlContact.setLayout(pnlContactLayout);
        pnlContactLayout.setHorizontalGroup(
            pnlContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblContactFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlContactLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(pnlContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldName, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContactLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        pnlContactLayout.setVerticalGroup(
            pnlContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblContactFill)
                .addGap(18, 18, 18)
                .addComponent(txtFldName, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txtFldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlContactUsLayout = new javax.swing.GroupLayout(pnlContactUs);
        pnlContactUs.setLayout(pnlContactUsLayout);
        pnlContactUsLayout.setHorizontalGroup(
            pnlContactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactUsLayout.createSequentialGroup()
                .addGroup(pnlContactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContactUsLayout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(lblContactImage, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(pnlContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContactUsLayout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(lblContactHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1775, Short.MAX_VALUE))
        );
        pnlContactUsLayout.setVerticalGroup(
            pnlContactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactUsLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblContactHeading)
                .addGroup(pnlContactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContactUsLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(pnlContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlContactUsLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(lblContactImage, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(499, Short.MAX_VALUE))
        );

        tabPaneWatchInfo.addTab("Contact Us", pnlContactUs);

        javax.swing.GroupLayout pnlWatchInfoScreenLayout = new javax.swing.GroupLayout(pnlWatchInfoScreen);
        pnlWatchInfoScreen.setLayout(pnlWatchInfoScreenLayout);
        pnlWatchInfoScreenLayout.setHorizontalGroup(
            pnlWatchInfoScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWatchInfoScreenLayout.createSequentialGroup()
                .addGroup(pnlWatchInfoScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMainBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlWatchInfoScreenLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(tabPaneWatchInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlWatchInfoScreenLayout.setVerticalGroup(
            pnlWatchInfoScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWatchInfoScreenLayout.createSequentialGroup()
                .addComponent(pnlMainBar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPaneWatchInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WatchIS");
        setBounds(new java.awt.Rectangle(0, 0, 1500, 1200));
        setMinimumSize(new java.awt.Dimension(1500, 1200));
        setSize(new java.awt.Dimension(1500, 1200));

        pnlMainScreen.setBackground(new java.awt.Color(3, 37, 76));
        pnlMainScreen.setBounds(new java.awt.Rectangle(0, 0, 1500, 1200));
        pnlMainScreen.setMaximumSize(new java.awt.Dimension(1500, 1200));
        pnlMainScreen.setMinimumSize(new java.awt.Dimension(1500, 1200));
        pnlMainScreen.setPreferredSize(new java.awt.Dimension(1500, 1200));

        lblLogoImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/WatchIS/resources/WatchLogo.png"))); // NOI18N
        lblLogoImage.setBounds(new java.awt.Rectangle(700, 0, 42, 17));

        lblWelcomePage.setFont(new java.awt.Font("Kannada MN", 1, 36)); // NOI18N
        lblWelcomePage.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcomePage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomePage.setText("WELCOME TO OUR PAGE");

        lblWait.setFont(new java.awt.Font("Kannada MN", 1, 24)); // NOI18N
        lblWait.setForeground(new java.awt.Color(255, 255, 255));
        lblWait.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWait.setText("Please Wait.........................");

        lblWelcomeDescription.setBackground(new java.awt.Color(51, 51, 0));
        lblWelcomeDescription.setFont(new java.awt.Font("Kannada MN", 0, 13)); // NOI18N
        lblWelcomeDescription.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcomeDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeDescription.setText("Here, you will get your desired watch in best quality and valuable prices with warranty cards.");

        lblMotto.setFont(new java.awt.Font("Herculanum", 1, 24)); // NOI18N
        lblMotto.setForeground(new java.awt.Color(255, 204, 0));
        lblMotto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMotto.setText("\"YOUR WRIST DESERVES THE BEST\"");

        javax.swing.GroupLayout pnlMainScreenLayout = new javax.swing.GroupLayout(pnlMainScreen);
        pnlMainScreen.setLayout(pnlMainScreenLayout);
        pnlMainScreenLayout.setHorizontalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcomePage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLogoImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMotto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainScreenLayout.createSequentialGroup()
                .addGap(0, 408, Short.MAX_VALUE)
                .addComponent(pgBarSplashScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400))
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcomeDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainScreenLayout.createSequentialGroup()
                        .addComponent(lblWait, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnlMainScreenLayout.setVerticalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(lblWelcomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWelcomeDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLogoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMotto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pgBarSplashScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWait, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(486, 486, 486))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        getContentPane().add(pnlLoginScreen, "LoginScreen");
        getContentPane().add(pnlMainScreen, "MainScreen");
        getContentPane().add(pnlWatchInfoScreen, "WatchInfoScreen");
        // Start with the loading screen
        cardLayout.show(getContentPane(), "MainScreen");
    }
    private void Progress() {
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(30); // Simulated delay for progress bar
                    publish(i);
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int progress = chunks.get(chunks.size() - 1);
                pgBarSplashScreen.setValue(progress);
            }

            @Override
            protected void done() {
               loadScreen("LoginScreen");  // Switch to login screen
            }
        };
        worker.execute();
    }
    private void txtFldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldPasswordActionPerformed

    private void txtFldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldUserNameActionPerformed
    // Method to switch screens
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String UserName = txtFldUserName.getText();
        String Password = new String(txtFldPassword.getText());

        // Checking if username or password is empty
        if (UserName.isEmpty() || Password.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Please Fill the textFields");
        } // Check if username and password are incorrect
        else if (!UserName.equals("santoshi") || !Password.equals("santoshi")) {
            JOptionPane.showMessageDialog(this,"The Input Does Not Matches. Please Try Again");
        } // If the inputs are correct, proceed to load the mInfo screen
        else {
            loadScreen("WatchInfoScreen"); // Load the Info screen
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void ckBoxRememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckBoxRememberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckBoxRememberActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        txtFldPassword.setText("");
        txtFldUserName.setText("");
        loadScreen("LoginScreen"); // Load the main screen
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void txtFldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldNameActionPerformed

    private void txtFldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldEmailActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendActionPerformed

    private void tfBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBrandActionPerformed

    private void tfPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPriceActionPerformed

    private void tfWarrantyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfWarrantyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfWarrantyActionPerformed

    private void btnAddWatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWatchActionPerformed
      
    }//GEN-LAST:event_btnAddWatchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tfSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSerialNumberActionPerformed
 
    /**
     * @param args the command line arguments
     */
   

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Watch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Watch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Watch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Watch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

                Watch IS = new Watch();

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(() -> {
            IS.setVisible(true);
        });

        IS.Progress();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Watch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxtAreaMessage;
    private javax.swing.JButton btnAddWatch;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox ckBoxRemember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl5k;
    private javax.swing.JLabel lblAboutUsHeading;
    private javax.swing.JLabel lblAboutUsImage;
    private javax.swing.JLabel lblAboutUsWording;
    private javax.swing.JLabel lblAboutUsWording1;
    private javax.swing.JLabel lblAboutUsWording2;
    private javax.swing.JLabel lblAboutUsWording3;
    private javax.swing.JLabel lblAboutUsWording4;
    private javax.swing.JLabel lblAboutUsWording5;
    private javax.swing.JLabel lblAboutUsWording6;
    private javax.swing.JLabel lblContactFill;
    private javax.swing.JLabel lblContactHeading;
    private javax.swing.JLabel lblContactImage;
    private javax.swing.JLabel lblExperiences;
    private javax.swing.JLabel lblExperiences1;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblForm;
    private javax.swing.JLabel lblHomeImage;
    private javax.swing.JLabel lblHomeWatchImage;
    private javax.swing.JLabel lblHomeWording;
    private javax.swing.JLabel lblHomeWording1;
    private javax.swing.JLabel lblHomeWording2;
    private javax.swing.JLabel lblHomeWording4;
    private javax.swing.JLabel lblInfoscreenLogo;
    private javax.swing.JLabel lblLoginDesc;
    private javax.swing.JLabel lblLoginImage;
    private javax.swing.JLabel lblLoginLogoImage;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoImage;
    private javax.swing.JLabel lblMatteWork;
    private javax.swing.JLabel lblMotto;
    private javax.swing.JLabel lblSale;
    private javax.swing.JLabel lblTimex;
    private javax.swing.JLabel lblWait;
    private javax.swing.JLabel lblWarranty;
    private javax.swing.JLabel lblWatchImage;
    private javax.swing.JLabel lblWatchImageHome;
    private javax.swing.JLabel lblWatchdetails;
    private javax.swing.JLabel lblWelcomeDescription;
    private javax.swing.JLabel lblWelcomePage;
    private javax.swing.JLabel lblYears;
    private javax.swing.JLabel lblhomeWording5;
    private javax.swing.JProgressBar pgBarSplashScreen;
    private javax.swing.JPanel pnlAboutUs;
    private javax.swing.JPanel pnlContact;
    private javax.swing.JPanel pnlContactUs;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlHomeDetails;
    private javax.swing.JPanel pnlLoginImage;
    private javax.swing.JPanel pnlLoginLogo;
    private javax.swing.JPanel pnlLoginScreen;
    private javax.swing.JPanel pnlMainBar;
    private javax.swing.JPanel pnlMainScreen;
    private javax.swing.JPanel pnlWatchCollections;
    private javax.swing.JPanel pnlWatchInfoScreen;
    private javax.swing.JScrollPane scrlPaneWatchDetails;
    private javax.swing.JScrollPane scrlPaneWatchInfo;
    private javax.swing.JTabbedPane tabPaneWatchInfo;
    private javax.swing.JTable tblWatchInfo;
    private javax.swing.JTextField tfBrand;
    private javax.swing.JTextField tfModelNumber;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfSerialNumber;
    private javax.swing.JTextField tfWarranty;
    private javax.swing.JTextField txtFldEmail;
    private javax.swing.JTextField txtFldName;
    private javax.swing.JTextField txtFldPassword;
    private javax.swing.JTextField txtFldUserName;
    // End of variables declaration//GEN-END:variables
}
